#TODO : add epel repo
#TODO : yum --enablerepo=epel  install collectd -y
- name: install fedora epel-release-7-6 repo for collectd
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm state=present

- name: install collectd
  yum: name=collectd state=installed

- name: ensure service collectd started
  service:
       name: collectd
       state: started
       enabled: yes
  when: dockerbuild is undefined

- name: ensure package libsemanage-python is installed
  yum: name=libsemanage-python state=installed

- name: collectd_tcp_network_connect allowed
  seboolean: name=collectd_tcp_network_connect state=yes persistent=yes
  when: dockerbuild is undefined

- name: install the collectd-lvm plugin rpm from a remote repo
  yum:
    name: collectd-lvm
    state: installed
