---

- name: download /etc/ansible/facts.d/rcip_openshift.fact from github
  get_url:
    url: https://raw.githubusercontent.com/talset/openshift-tools/549712d50c8ca21f75241d3247b7466d52f9da8c/ansible/fact/rcip_openshift.fact
    dest: /etc/ansible/facts.d/rcip_openshift.fact
    mode: 0755
  tags: service_ips
  when: deployment_type is defined and ( deployment_type in ['entreprise'] )

- name: download /etc/ansible/facts.d/rcip_openshift.fact from github
  get_url:
    url: https://raw.githubusercontent.com/talset/openshift-tools/master/ansible/fact/rcip_openshift.fact
    dest: /etc/ansible/facts.d/rcip_openshift.fact
    mode: 0755
  tags: service_ips
  when: deployment_type is defined and ( deployment_type in ['origin', 'openshift-entreprise'] )

- name: re-read facts after adding custom fact rcip
  setup: filter=ansible_local
  tags: service_ips

#need to add into no_proxy
#- debug: msg="the current date is {% for host in hostvars[groups['masters'][0]].ansible_local.rcip_openshift.service.values() %},{{ host }}{% endfor %}"
#  tags: service_ips
