---

- name: copy fact rcip_openshift.fact
  copy:
    src: ../../files/etc/ansible/facts.d/rcip_openshift.fact
    dest: /etc/ansible/facts.d/rcip_openshift.fact
    mode: 0755
  tags: service_ips

- name: re-read facts after adding custom fact rcip
  setup: filter=ansible_local
  tags: service_ips
