---

- name: copy fact rcip_openshift.fact for enterprise version
  copy:
    src: ../../files/etc/ansible/facts.d/rcip_openshift.fact_enterprise
    dest: /etc/ansible/facts.d/rcip_openshift.fact
    mode: 0755
  tags: service_ips
  when: deployment_type is defined and ( deployment_type in ['enterprise'] )

- name: copy fact rcip_openshift.fact for openshift-enterprise version
  copy:
    src: ../../files/etc/ansible/facts.d/rcip_openshift.fact_openshift-enterprise
    dest: /etc/ansible/facts.d/rcip_openshift.fact
    mode: 0755
  tags: service_ips
  when: deployment_type is defined and ( deployment_type in ['origin', 'openshift-enterprise'] )

- name: re-read facts after adding custom fact rcip
  setup: filter=ansible_local
  tags: service_ips

#need to add into no_proxy
#- debug: msg="the current date is {% for host in hostvars[groups['masters'][0]].ansible_local.rcip_openshift.service.values() %},{{ host }}{% endfor %}"
#  tags: service_ips
