---
- name: install postfix
  yum:
    name: postfix

- name: start and enable postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: change myorigin if needed
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^myorigin ='
    line: "myorigin = {{ postfix_myorigin }}"
  when: postfix_myorigin is defined
  notify: restart postfix

- name: change relayhost if needed
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^relayhost ='
    line: "relayhost = {{ postfix_relayhost }}"
  when: postfix_relayhost is defined
  notify: restart postfix
