- name: clone rcip-openshift-scripts in local to copy on atomic host
  environment: proxy_env
  git:
     repo: https://github.com/redhat-cip/rcip-openshift-scripts.git
     dest: /tmp/rcip-openshift-scripts
  delegate_to: 127.0.0.1
  run_once: true

- name: copy rcip-openshift-scripts on atomic host
  copy:
    src: /tmp/rcip-openshift-scripts
    dest: /opt/
