---
- include: fact.yml
  tags: fact
- include: bashrc.yml
- include: subscription.yml
  when: subscription_pool is defined and subscription_pool

- include: package.yml
  when: not ansible_local.system.is_atomic | bool
