---

#debug packages

  - name: subscription-manager register and attach pool
    redhat_subscription:
       state: present
       username: "{{ subscription_name }}"
       password: "{{ subscription_pass }}"
       autosubscribe: true
       pool: "{{ subscription_pool }}"
       #pool: '^Employee SKU$'

  - shell: subscription-manager repos --disable='*'
  - shell: subscription-manager repos --enable='rhel-7-server-rpms' --enable='rhel-7-server-extras-rpms' --enable='rhel-7-server-ose-3.0-rpms' --enable='rhel-7-server-optional-rpms'
