---
- name: allow dns query
  command: "{{ item }}"
  with_items:
    - /usr/sbin/iptables -I INPUT 1 -p tcp --dport 53 -s 0.0.0.0/0 -j ACCEPT
    - /usr/sbin/iptables -I INPUT 1 -p udp --dport 53 -s 0.0.0.0/0 -j ACCEPT
