---
- name: add .bashrc if missing
  file:
    dest: /root/.bashrc
    owner: root
    state: touch
  when: ansible_local.system.is_atomic | bool

- name: add .etcd.bashrc file
  template:
    dest: /root/.etcd.bashrc
    src: root/etcd.bashrc.j2
  when: "inventory_hostname not in groups['etcd']"
