---
- name: directory to exports
  file:
      path: "{{ item.path }}"
      state: directory
      mode: 0755
      owner: nfsnobody
      group: nfsnobody
  with_items:
      - { path: '/var/export/' }
      - { path: '/var/export/vol1' }
      - { path: '/var/export/vol2' }
      - { path: '/var/export/vol3' }
      - { path: '/var/export/vol4' }
      - { path: '/var/export/vol5' }
      - { path: '/var/export/vol6' }

- name: add exports line
  lineinfile:
    dest: /etc/exports
    line: "{{ item.line }}"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart the NFS server
  with_items:
    - { line: '/var/export/vol1 *(rw,sync,all_squash)' }
    - { line: '/var/export/vol2 *(rw,sync,all_squash)' }
    - { line: '/var/export/vol3 *(rw,sync,all_squash)' }
    - { line: '/var/export/vol4 *(rw,sync,all_squash)' }
    - { line: '/var/export/vol5 *(rw,sync,all_squash)' }
    - { line: '/var/export/vol6 *(rw,sync,all_squash)' }

- name: Add iptables NFS
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^COMMIT$"
  with_items:
    - { regexp: '^-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53248 -j ACCEPT$', line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 53248 -j ACCEPT' }
    - { regexp: '^-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 50825 -j ACCEPT$', line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 50825 -j ACCEPT' }
    - { regexp: '^-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 20048 -j ACCEPT$', line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 20048 -j ACCEPT' }
    - { regexp: '^-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT$', line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 2049 -j ACCEPT' }
    - { regexp: '^-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT$', line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 111 -j ACCEPT' }
  notify:
        - Add nfs iptables rules


#systemctl enable rpcbind nfs-server
#systemctl start rpcbind nfs-server nfs-lock 
#systemctl start nfs-idmap
