---
- name: add script to setup serviceaccount
  copy:
    src: 'tmp/metrics_sa.sh'
    dest: '/tmp/metrics_sa.sh'
    owner: root
    mode: 0700

- name: run /tmp/metrics_sa.sh to setup serviceaccount and grab token
  command: /tmp/metrics_sa.sh
  always_run: yes
  register: token_metrics

- name: create fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: add token metrics to fact openshift_data
  ini_file:
    dest: /etc/ansible/facts.d/openshift_data.fact
    section: tokens
    option: metrics
    value: "{{ token_metrics.stdout }}"
  when: token_metrics|success

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
