---
- name: add script to setup serviceaccount
  copy:
    src: "tmp/{{ item }}_sa.sh"
    dest: "/tmp/{{ item }}_sa.sh"
    owner: root
    mode: 0700
  with_items:
    - metrics
    - monitoring


- name: create fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: run /tmp/metrics_sa.sh to setup serviceaccount and grab token
  command: /tmp/metrics_sa.sh
  always_run: yes
  register: token_metrics

- name: add token metrics to fact openshift_data
  ini_file:
    dest: /etc/ansible/facts.d/openshift_data.fact
    section: tokens
    option: metrics
    value: "{{ token_metrics.stdout }}"
  when: token_metrics|success

- name: run /tmp/monitoring_sa.sh to setup serviceaccount and grab token
  command: /tmp/monitoring_sa.sh
  always_run: yes
  register: token_monitoring

- name: add token monitoring to fact openshift_data
  ini_file:
    dest: /etc/ansible/facts.d/openshift_data.fact
    section: tokens
    option: monitoring
    value: "{{ token_monitoring.stdout }}"
  when: token_monitoring|success

- name: re-read facts after adding custom fact
  setup: filter=ansible_local
