---
- name: add script to setup serviceaccount
  copy:
    src: 'tmp/metrics_sa.sh'
    dest: '/tmp/metrics_sa.sh'
    owner: root
    mode: 0700
- name: run script to setup serviceaccount and local fact
  command: /tmp/metrics_sa.sh
  args:
    creates: /etc/ansible/facts.d/openshift_data.fact
- name: re-read facts after adding custom fact
  setup: filter=ansible_local
