---
- name: write Sensu check JSON config
  copy:
    src: "etc/sensu/conf.d/check_{{ item }}.json"
    dest: "/etc/sensu/conf.d/check_{{ item }}.json"
  notify:
    - restart sensu-server
    - restart sensu-api
  tags: sensu monitoring
  with_items:
    - default
    - openshift-node

- name: write Sensu default_openshift-master.json
  template: src=etc/sensu/conf.d/check_openshift-master.json.j2 dest=/etc/sensu/conf.d/check_openshift-master.json
  notify:
    - restart sensu-server
    - restart sensu-api
  tags: sensu monitoring

- name: write Sensu default_etcd.json
  template:
    src: etc/sensu/conf.d/check_etcd.json.j2
    dest: /etc/sensu/conf.d/check_etcd.json
  notify:
    - restart sensu-server
    - restart sensu-api
  tags: sensu monitoring
