---
- name: sensu mailer handler config
  template:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       mode: 0644
  notify:
       - restart sensu-server
       - restart sensu-api
  with_items:
       - { src: 'etc/sensu/conf.d/handler_mailer.json.j2', dest: '/etc/sensu/conf.d/handler_mailer.json' }
       - { src: 'etc/sensu/conf.d/mailer.json.j2', dest: '/etc/sensu/conf.d/mailer.json' }

- name: gem install mail
  environment: proxy_env
  gem: name=mail state=present user_install=no

  #/usr/local/bin/handler-mailer.rb
- name: gem install sensu-plugins-mailer
  environment: proxy_env
  gem: name=sensu-plugins-mailer state=present user_install=no
