- name: install wget
  yum: name=wget state=installed

#TODO : add epel repo
#TODO : yum --enablerepo=epel  install collectd -y
- name: install fedora epel-release-7-5 repo for collectd
  yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present

- name: install collectd
  yum: name=collectd state=installed

- name: ensure service collectd started
  service:
       name: collectd
       state: started
       enabled: yes

- name: ensure package libsemanage-python is installed
  yum: name=libsemanage-python state=installed

- seboolean: name=collectd_tcp_network_connect state=yes persistent=yes

- name: install the collectd-lvm plugin rpm from a remote repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/7/x86_64/c/collectd-lvm-5.5.0-2.el7.x86_64.rpm
    state: present

- name: config /etc/collectd.conf
  lineinfile:
    dest: /etc/collectd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify:
      - restart collectd
  with_items:
    - regexp: '^FQDNLookup'
      line: 'FQDNLookup false'
    - { regexp: '^Hostname .*$', line: "Hostname {{ ansible_fqdn }}" }
    - { regexp: '^Include "/etc/collectd.d"$', line: 'Include "/etc/collectd.d"' }

- name: collectd plugins configurations
  template:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       mode: 0644
  notify:
       - restart collectd
  with_items:
       - { src: 'etc/collectd.d/write_graphite.conf.j2', dest: '/etc/collectd.d/write_graphite.conf' }
       - { src: 'etc/collectd.d/cpu.conf.j2', dest: '/etc/collectd.d/cpu.conf' }
       - { src: 'etc/collectd.d/df.conf.j2', dest: '/etc/collectd.d/df.conf' }
       - { src: 'etc/collectd.d/disk.conf.j2', dest: '/etc/collectd.d/disk.conf' }
       - { src: 'etc/collectd.d/exec.conf.j2', dest: '/etc/collectd.d/exec.conf' }
       - { src: 'etc/collectd.d/interface.conf.j2', dest: '/etc/collectd.d/interface.conf' }
       - { src: 'etc/collectd.d/load.conf.j2', dest: '/etc/collectd.d/load.conf' }
       - { src: 'etc/collectd.d/lvm.conf.j2', dest: '/etc/collectd.d/lvm.conf' }
       - { src: 'etc/collectd.d/memory.conf.j2', dest: '/etc/collectd.d/memory.conf' }
