---
- name: loglevel docker
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: '^OPTIONS=.*'
    line: "OPTIONS='{{ docker_options }}'"
  notify:
      - restart docker

- name: http_proxy docker
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^HTTP_PROXY=.*', line: "HTTP_PROXY='{{ proxy_env[\'http_proxy\'] }}'" }
    - { regexp: '^NO_PROXY=.*', line: "NO_PROXY='{{ no_proxy }},{{ openshift_vip_fqdn_internal }}{% for host in groups['all'] %},{{ hostvars[host].get(\"inventory_hostname\") }}{% endfor %}'" }
  notify:
      - restart docker
  when: proxy_env['http_proxy'] is defined

- name: config /etc/sysconfig/docker-storage-setup
  lineinfile:
    dest: /etc/sysconfig/docker-storage-setup
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
#  notify:
#      - configure docker on lvm
  with_items:
    - { regexp: '^DEVS=.*$', line: "DEVS=/dev/{{ docker_storage_dev }}" }
    - { regexp: '^VG=.*$', line: 'VG=docker-vg' }
    - { regexp: '^SETUP_LVM_THIN_POOL=.*$', line: 'SETUP_LVM_THIN_POOL=yes' }


- name: config /etc/sysconfig/docker-storage
  lineinfile:
    dest: /etc/sysconfig/docker-storage
    regexp: '^DOCKER_STORAGE_OPTIONS=.*'
    line: "DOCKER_STORAGE_OPTIONS=-s devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker--vg-docker--pool"
  #notify:
  #    - restart docker
