---

- name: loglevel sensu present
  lineinfile:
    dest: /etc/default/sensu
    regexp: '^LOG_LEVEL=.*$'
    line: 'LOG_LEVEL={{ loglevel_sensuclient }}'
    state: present
  notify:
          - restart sensu-client
