---
- name: Import elasticsearch gpg key
  environment: proxy_env
  rpm_key: state=present key=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add repos /etc/yum.repos.d/logstash.repo
  template:
       src: "etc/yum.repos.d/repo.template.j2"
       dest: "/etc/yum.repos.d/logstash.repo"
       owner: root
       group: root
       mode: 0644
  with_items:
       - { name: "logstash-{{ monitoring_elasticsearch_version }}",
           baseurl: "http://packages.elasticsearch.org/logstash/{{ monitoring_logstash_version }}/centos",
           gpgcheck: 1,
           gpgkey: 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch',
           enabled: 1 }

- name: install logstash dependances
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
      - java-1.8.0-openjdk
      - which

- name: install logstash
  yum: name=logstash state=installed

- name: ensure service logstash started
  service:
       name: logstash
       state: started
       enabled: yes
  when: dockerbuild is undefined

- name: Allow logstash on messages
  file:
    path: /var/log/messages
    owner: root
    group: logstash
    mode: 0640
    state: touch

- name: Setup additionnal plugins for logstash
  shell: "/opt/logstash/bin/plugin install {{ item }} > /opt/logstash/{{ item }}.log"
    creates: "/opt/logstash/{{ item }}.log"
  with_items:
     - logstash-input-journald
     - logstash-filter-kubernetes
