---
- include: sysctl.yml
- include: openshift-node.yml
- include: udev_fix.yml
- include: docker.yml
- include: nfs.yml
- include: scripts.yml
- include: crontab.sh
- include: logstash.yml
  tags:
    - logstash
    - log-client
  when: "'monitoring' in groups and not ansible_local.system.is_atomic | bool"

- include: logstash_config.yml
  tags:
    - logstash
    - log-client
  when: "'monitoring' in groups"
