---
- include: sysctl.yml
- include: openshift-node.yml
- include: udev_fix.yml
- include: docker.yml
- include: nfs.yml
- include: scripts.yml
- include: crontab.sh
- include: collectd.yml
  tags:
    - collectd
  when: "'monitoring' in group_names"
- include: logstash.yml
  when: "'monitoring' in group_names"
