---
- name: loglevel openshift-node
  lineinfile:
    dest: "/etc/sysconfig/{{ nodes_deamon_name }}"
    regexp: '^OPTIONS=(.*)--loglevel=[0-9](.*)$'
    line: 'OPTIONS=\1--loglevel={{ loglevel_openshift_node }}\2'
    backrefs: yes
  notify:
        - restart openshift-node

- name: http_proxy openshift-node
  lineinfile:
    dest: "/etc/sysconfig/{{ nodes_deamon_name }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^HTTP_PROXY=.*', line: "HTTP_PROXY='{{ proxy_env[\'http_proxy\'] }}'" }
    - { regexp: '^HTTPS_PROXY=.*', line: "HTTPS_PROXY='{{ proxy_env[\'https_proxy\'] }}'" }
    - { regexp: '^NO_PROXY=.*', line: "NO_PROXY='{{ no_proxy }},{{ openshift_master_cluster_hostname }}{% for host in groups['all'] %},{{ hostvars[host].get(\"inventory_hostname\") }}{% endfor %}{% for ns in hostvars[groups[\"masters\"][0]].ansible_local.rcip_openshift.values() %}{% for ip in ns.services.values() %},{{ip}}{% endfor %}{% endfor %}'" }
  notify:
      - restart openshift-node
  when: proxy_env['http_proxy']
  tags: proxyenv


- name: "ensure service {{ nodes_deamon_name }} started"
  service:
       name: "{{ nodes_deamon_name }}"
       state: started
       enabled: yes
