---
- name: loglevel openshift-node
  lineinfile:
    dest: /etc/sysconfig/openshift-node
    regexp: '^OPTIONS=(.*)--loglevel=[0-9](.*)$'
    line: 'OPTIONS=\1--loglevel={{ loglevel_openshift_node }}\2'
    backrefs: yes
  notify:
        - restart openshift-node



- name: DOCKER_NETWORK_OPTIONS mtu openshift-node
  lineinfile:
    dest: /etc/sysconfig/openshift-node
    regexp: '^DOCKER_NETWORK_OPTIONS=.*$'
    line: 'DOCKER_NETWORK_OPTIONS={{ docker_network_options }}'
  notify:
        - restart openshift-node

- name: http_proxy openshift-node
  lineinfile:
    dest: /etc/sysconfig/openshift-node
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^HTTP_PROXY=.*', line: "HTTP_PROXY='{{ proxy_env[\'http_proxy\'] }}'" }
    - { regexp: '^HTTPS_PROXY=.*', line: "HTTPS_PROXY='{{ proxy_env[\'https_proxy\'] }}'" }
  notify:
      - restart openshift-node
  when: proxy_env['http_proxy'] is defined



#Update max-pods in node-config.yaml max-pods 100
- name: Add kubeletArguments section in node-config.yaml
  lineinfile:
    dest: /etc/openshift/node/node-config.yaml
    line: 'kubeletArguments:'
  tags:
         - openshift-node

- name: Add max-pods in node-config.yaml
  lineinfile:
    dest: /etc/openshift/node/node-config.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
  with_items:
       - { line: "  max-pods:",    regexp: '^  max-pods:$',   insertafter: "^kubeletArguments:$"}
       - { line: "     - \"100\"", regexp: '     - "[0-9]+"', insertafter: "^  max-pods:$"}
  tags:
         - openshift-node
  notify:
        - restart openshift-node

- name: ensure service openshift-node started
  service:
       name: openshift-node
       state: started
       enabled: yes
