---

- name: ensure service sensu-client started
  service:
       name: sensu-client
       state: started
       enabled: yes


- name: loglevel sensu present
  lineinfile:
    dest: /etc/default/sensu
    regexp: '^LOG_LEVEL=.*$'
    line: 'LOG_LEVEL={{ loglevel_sensuclient }}'
    state: present
  notify:
          - restart sensu-client
