---

#Fix : https://access.redhat.com/solutions/369563
- name: additional param in sysctl (tcp_rmem and tcp_wmem)
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify:
      - reload sysctl
  tags:
      - nodes_sysctl
  with_items:
    - { regexp: '^net.ipv4.tcp_rmem =(.*)$', line: "net.ipv4.tcp_rmem = {{ nodes_sysctl_net_ipv4_tcp_rmem }}" }
    - { regexp: '^net.ipv4.tcp_wmem =(.*)$', line: "net.ipv4.tcp_wmem = {{ nodes_sysctl_net_ipv4_tcp_wmem }}" }
