---
#- name: udevadm control --timeout=300 and /etc/rc.local
#  lineinfile:
#    dest: /etc/rc.local
#    line: 'udevadm control --timeout=300'
#  notify:
#      - fix udev timeout
#      - restart docker

- name: Check if file has udev.event-timeout
  shell: grep 'udev.event-timeout' /etc/sysconfig/grub
  ignore_errors: True
  register: grep

- name: fix udevadm timeout kernel param
  lineinfile:
    dest: /etc/sysconfig/grub
    regexp: '^GRUB_CMDLINE_LINUX=(.*)"$'
    line: 'GRUB_CMDLINE_LINUX=\1 udev.event-timeout=300"'
    backrefs: yes
  when: grep.stdout.find("GRUB_CMDLINE_LINUX") != -1
  notify:
        - grub2-mkconfig
