---
- name: gem install sensu-plugins-etcd
  environment: proxy_env
  gem: name=sensu-plugins-etcd state=present user_install=no

- name: set permissions to etcd cert for sensu checks
  file:
     path: "/etc/etcd/peer.{{ item }}"
     owner: etcd
     group: sensu
     mode: 0640
  with_items:
    - key
    - crt
