---
- name: set permission to /etc/etcd for sensu
  file:
    path: /etc/etcd
    group: adm
    mode: g+rx
  when: dockerbuild is undefined

- name: set permissions to etcd cert for sensu checks
  file:
     path: "/etc/etcd/peer.{{ item }}"
     owner: etcd
     group: adm
     mode: 0640
  with_items:
    - key
    - crt
  when: dockerbuild is undefined
