---

- name: yum install installed
  yum: name=dnsmasq state=installed
  tags: dns

- name: config /etc/dnsmasq.d/external.conf
  copy:
    dest: /etc/dnsmasq.d/external.conf
    content: "{% for s in dns_servers %}server={{ s }}\n{% endfor %}"
  tags: dns
  notify: restart dns

- name: Add hostname into hosts for dnsmasq
  lineinfile:
     dest: /etc/hosts
     state: present
     line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}      {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: '{{groups["all"]}}'

- name: Add vip cluster
  lineinfile:
     dest: /etc/hosts
     state: present
     line: "{{ customer_api_public_vip }}    {{ openshift_master_cluster_hostname }}"
  when: customer_api_public_vip is defined and customer_api_public_vip

- name: ensure start dnsmasq
  service: name=dnsmasq state=started enabled=yes
  tags: dns

- name: allow port 53 iptables
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^-A INPUT -j REJECT"
  with_items:
    - { regexp: '^-A INPUT -p tcp --dport 53 -s 0.0.0.0/0 -j ACCEPT$', line: '-A INPUT -p tcp --dport 53 -s 0.0.0.0/0 -j ACCEPT' }
    - { regexp: '^-A INPUT -p udp --dport 53 -s 0.0.0.0/0 -j ACCEPT$', line: '-A INPUT -p udp --dport 53 -s 0.0.0.0/0 -j ACCEPT' }
  notify:
        - allow dns query

