---
- name: Install Graphite Dependencies for Redhat
  yum: "name={{ item }} state=present"
  with_items:
    - gcc
    - mod_wsgi
    - python-pip
    - python-devel

- name: install pip packages
  pip: "name={{ item }} state=present"
  environment:
    http_proxy: "{{ proxy_env['http_proxy'] }}"
    https_proxy: "{{ proxy_env['https_proxy'] }}"
    CFLAGS: '-march=x86-64'
    PYTHONPATH: "/opt/graphite/lib:/opt/graphite/webapp"
  with_items:
    - django-tagging==0.3.6
    - django
    - "https://github.com/graphite-project/ceres/archive/{{ ceres_commit }}.zip"
    - whisper
    - "https://github.com/graphite-project/carbon/archive/{{ carbon_commit }}.zip"
    - graphite-web

- name: set carbon.conf
  command: cp /opt/graphite/conf/carbon.conf.example /opt/graphite/conf/carbon.conf
  args:
    creates: /opt/graphite/conf/carbon.conf

- name: set graphite.wsgi
  copy:
    src: opt/graphite/conf/graphite.wsgi
    dest: /opt/graphite/conf/graphite.wsgi

- name: setup carbon storage
  copy:
    src: opt/graphite/conf/storage-schemas.conf
    dest: /opt/graphite/conf/storage-schemas.conf

- name: setup carbon storage aggregation
  copy:
    src: opt/graphite/conf/storage-aggregation.conf
    dest: /opt/graphite/conf/storage-aggregation.conf

- name: add graphite user
  user: name=graphite

- name: create systemd unit for carbon-cache
  copy:
    src: etc/systemd/system/carbon-cache.service
    dest: /etc/systemd/system/carbon-cache.service
  notify:
    - daemon-reload

- name: Set right permissions for some dir in /opt/graphite
  file:
    path: "/opt/graphite/storage{{ item }}"
    owner: graphite
    group: apache
    mode: 0775
    state: directory
  with_items:
    - ""
    - "/log"
    - "/log/webapp"
    - "/whisper"

# TODO: use template with variable password for mysql, port ...
- name: configure graphite-web
  copy:
    src: opt/graphite/webapp/graphite/local_settings.py
    dest: /opt/graphite/webapp/graphite/local_settings.py

- name: Start carbon cache
  service: name=carbon-cache state=running enabled=yes

# TODO: Use mysql no sqlitedb
- name: Setup sqlitedb
  command: /usr/bin/python manage.py syncdb --noinput chdir=/opt/graphite/webapp/graphite
   creates=/opt/graphite/storage/graphite.db
  sudo_user: apache
  register: sqlite_setup

- name: Wait for sqlitedb to be setup
  shell: sleep 3
  when: sqlite_setup.changed

- name: set permission on graphite.db
  file:
    path: /opt/graphite/storage/graphite.db
    owner: graphite
    group: apache
    mode: 0660

- name: add port 3003 to httpd.conf
  lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='^Listen 3003$' line='Listen 3003'
  notify: restart httpd
