---
- name: Install Graphite Dependencies for Redhat
  yum: "name={{ item }} state=present"
  with_items:
    - gcc
    - mod_wsgi
    - python-pip
    - python-devel

- name: install pip packages
  pip: "name={{ item }} state=present"
  environment:
    http_proxy: "{{ proxy_env['http_proxy'] }}"
    https_proxy: "{{ proxy_env['https_proxy'] }}"
    CFLAGS: '-march=x86-64'
    PYTHONPATH: "/opt/graphite/lib:/opt/graphite/webapp"
  with_items:
    - django-tagging==0.3.6
    - django
    - "https://github.com/graphite-project/ceres/archive/{{ ceres_commit }}.zip"
    - whisper
    - "https://github.com/graphite-project/carbon/archive/{{ carbon_commit }}.zip"
    - graphite-web

- name: set carbon.conf
  command: cp /opt/graphite/conf/carbon.conf.example /opt/graphite/conf/carbon.conf
  args:
    creates: /opt/graphite/conf/carbon.conf

- name: set graphite.wsgi
  copy:
    src: opt/graphite/conf/graphite.wsgi
    dest: /opt/graphite/conf/graphite.wsgi

- name: setup carbon storage
  copy:
    src: opt/graphite/conf/storage-schemas.conf
    dest: /opt/graphite/conf/storage-schemas.conf

- name: setup carbon storage aggregation
  copy:
    src: opt/graphite/conf/storage-aggregation.conf
    dest: /opt/graphite/conf/storage-aggregation.conf

- name: add graphite user
  user: name=graphite

- name: create systemd unit for carbon-cache
  copy:
    src: etc/systemd/system/carbon-cache.service
    dest: /etc/systemd/system/carbon-cache.service
  notify:
    - daemon-reload

- name: Set right permissions for some dir in /opt/graphite
  file:
    path: "/opt/graphite/storage{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - ""
    - "/log"
    - "/log/webapp"
    - "/whisper"
- name: Set right owner:groups recursively for /opt/graphite/storage...
  file:
    path: "/opt/graphite/{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: apache
    state: directory
    recurse: yes
  with_items:
    - { dir: "storage", owner: "graphite" }
    - { dir: "storage/log/webapp", owner: "apache" }

- name: check if SELinux fcontext is present 
  shell: semanage fcontext -l | grep '/opt/graphite/storage/log/webapp(/.*)?' | grep httpd_log_t
  ignore_errors: yes
  changed_when: False
  always_run: yes
  register: context_present

- name: Set SELinux fcontext for apache to be able to use log dir for wsgi
  command: "{{ item }}"
  with_items:
    - semanage fcontext -a -t httpd_log_t "/opt/graphite/storage/log/webapp(/.*)?"
    - restorecon -R -v /opt/graphite/storage/log/webapp
  when: context_present|failed

- name: check if SELinux fcontext is present for graphite.db
  shell: semanage fcontext -l | grep '/opt/graphite/storage/graphite.db' | grep httpd_log_t
  ignore_errors: yes
  changed_when: False
  always_run: yes
  register: context_db_present

- name: Set SELinux fcontext for graphite.db
  command: "{{ item }}"
  with_items:
    - semanage fcontext -a -t httpd_log_t "/opt/graphite/storage/graphite.db"
    - restorecon -R -v /opt/graphite/storage/
  when: context_db_present|failed

# TODO: use template with variable password for mysql, port ...
- name: configure graphite-web
  copy:
    src: opt/graphite/webapp/graphite/local_settings.py
    dest: /opt/graphite/webapp/graphite/local_settings.py

- name: Start carbon cache
  service: name=carbon-cache state=running enabled=yes

# TODO: Use mysql no sqlitedb
- name: Setup sqlitedb
  command: /usr/bin/python manage.py migrate --noinput chdir=/opt/graphite/webapp/graphite
   creates=/opt/graphite/storage/graphite.db
  sudo_user: apache
  register: sqlite_setup

- name: Wait for sqlitedb to be setup
  shell: sleep 3
  when: sqlite_setup.changed

- name: set permission on graphite.db
  file:
    path: /opt/graphite/storage/graphite.db
    owner: apache
    group: apache
    mode: 0660
