---
- yum: name=postfix state=installed
- service: name=postfix state=started enabled=yes
- lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^myorigin ='
    line: "myorigin = {{ postfix_myorigin }}"
  when: postfix_myorigin is defined
  register: postfixrestart
- lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^relayhost ='
    line: "relayhost = {{ postfix_relayhost }}"
  when: postfix_relayhost is defined
  register: postfixrestart
- when: postfixrestart
  service: name=postfix state=restarted
