---

#debug packages
- name: [ common | install nmap-ncat ]
  yum: name=nmap-ncat state=installed

- name: [ common | install tcpdump ]
  yum: name=tcpdump state=installed

- name: [ common | install vim ]
  yum: name=vim state=installed
