---
- name: install httpd
  yum: name=httpd state=installed

- name: install mod_ssl
  yum: name=mod_ssl state=installed

- file: dest=/etc/httpd/conf.d/ssl.conf state=absent

- name: install mod_wsgi
  yum: name=mod_wsgi state=installed

- name: httpd security rules (iptables / selinux)
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^-A INPUT -j REJECT"
  with_items:
    - { regexp: "^-A INPUT -p tcp --dport {{ httpd_sensu_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ httpd_sensu_port }} -s 0.0.0.0/0 -j ACCEPT" }
    - { regexp: "^-A INPUT -p tcp --dport {{ httpd_grafana_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ httpd_grafana_port }} -s 0.0.0.0/0 -j ACCEPT" }
    - { regexp: "^-A INPUT -p tcp --dport {{ httpd_kibana_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ httpd_kibana_port }} -s 0.0.0.0/0 -j ACCEPT" }
    - { regexp: "^-A INPUT -p tcp --dport {{ rabbitmq_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ rabbitmq_port }} -s 0.0.0.0/0 -j ACCEPT" }
    - { regexp: "^-A INPUT -p tcp --dport {{ carbon_port }} -s 0.0.0.0/0 -j ACCEPT$", line: "-A INPUT -p tcp --dport {{ carbon_port }} -s 0.0.0.0/0 -j ACCEPT" }
  notify:
        - httpd security rules

- meta: flush_handlers

- name: Set httpd_can_network_connect to true for log access
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: httpd listen {{ httpd_daemon_graphite_port }} {{ httpd_sensu_port }} {{ httpd_grafana_port }} {{ httpd_kibana_port }}
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: "{{ item.line }}"
  with_items:
    - { line: "Listen {{ httpd_daemon_graphite_port }}" }
    - { line: "Listen {{ httpd_sensu_port }}" }
    - { line: "Listen {{ httpd_grafana_port }}" }
    - { line: "Listen {{ httpd_kibana_port }}" }
  notify:
    - restart httpd

- name: httpd configuration
  template:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       mode: 0644
  notify:
       - restart httpd
  with_items:
       - { src: 'etc/httpd/conf.d/grafana.conf.j2', dest: '/etc/httpd/conf.d/grafana.conf' }
       - { src: 'etc/httpd/conf.d/graphite-web.conf.j2', dest: '/etc/httpd/conf.d/graphite-web.conf' }
       - { src: 'etc/httpd/conf.d/sensu.conf.j2', dest: '/etc/httpd/conf.d/sensu.conf' }
       - { src: 'etc/httpd/conf.d/kibana.conf.j2', dest: '/etc/httpd/conf.d/kibana.conf' }

- name: ensure service httpd enabled
  service:
       name: httpd
       enabled: yes
