---
- name: install httpd
  yum: name=httpd state=installed

- name: install mod_ssl
  yum: name=mod_ssl state=installed

- file: dest=/etc/httpd/conf.d/ssl.conf state=absent

- name: install mod_wsgi
  yum: name=mod_wsgi state=installed

- name: httpd security rules (iptables / selinux)
  lineinfile:
    dest: /etc/sysconfig/iptables
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertbefore: "^-A INPUT -j REJECT"
  with_items:
    - { regexp: '^-A INPUT -p tcp --dport 443 -s 0.0.0.0/0 -j ACCEPT$', line: '-A INPUT -p tcp --dport 443 -s 0.0.0.0/0 -j ACCEPT' }
    - { regexp: '^-A INPUT -p tcp --dport 5672 -s 0.0.0.0/0 -j ACCEPT$', line: '-A INPUT -p tcp --dport 5672 -s 0.0.0.0/0 -j ACCEPT' }
    - { regexp: '^-A INPUT -p tcp --dport 2003 -s 0.0.0.0/0 -j ACCEPT$', line: '-A INPUT -p tcp --dport 2003 -s 0.0.0.0/0 -j ACCEPT' }
  notify:
        - httpd security rules

- name: httpd listen {{ graphite_port }} {{ sensu_httpd_port }} {{ grafana_httpd_port }} {{ kibana_httpd_port }}
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: "{{ item.line }}"
  with_items:
    - { line: "Listen {{ graphite_port }}" }
    - { line: "Listen {{ sensu_httpd_port }}" }
    - { line: "Listen {{ grafana_httpd_port }}" }
    - { line: "Listen {{ kibana_httpd_port }}" }
  notify:
    - restart httpd

#TODO: generate /etc/httpd/openshift-passwd
#chmod 600 /etc/httpd/openshift-passwd 
#chown apache /etc/httpd/openshift-passwd
#TODO: push cert monitoring_cert monitoring_key
#TODO : semanage port -a -t http_port_t -p tcp 3003

- name: httpd configuration
  template:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       mode: 0644
  notify:
       - restart httpd
  with_items:
       - { src: 'etc/httpd/conf.d/grafana.conf.j2', dest: '/etc/httpd/conf.d/grafana.conf' }
       - { src: 'etc/httpd/conf.d/graphite-web.conf.j2', dest: '/etc/httpd/conf.d/graphite-web.conf' }
       - { src: 'etc/httpd/conf.d/sensu.conf.j2', dest: '/etc/httpd/conf.d/sensu.conf' }
       - { src: 'etc/httpd/conf.d/kibana.conf.j2', dest: '/etc/httpd/conf.d/kibana.conf' }

- name: ensure service httpd started
  service:
       name: httpd
       state: started
       enabled: yes
