---
- name: mysql security rules
  command: "{{ item }}"
  with_items:
    - /usr/sbin/semanage port -a -t mysqld_port_t -p tcp 3306
    - /usr/sbin/iptables -I INPUT 1 -p tcp --dport 3306 -s 0.0.0.0/0 -j ACCEPT
