---
sensu_manage_docker_storage: "{{ manage_docker_storage | default('true') }}"

sensu_deployment_type: "{{ deployment_type | default('openshift') }}"
sensu_openshift_etc_config: "{% if deployment_type == 'origin' or deployment_type == 'openshift-enterprise' %}origin{% else %}openshift{% endif %}"

sensu_openshift_base_api: "{{ openshift_base_api | default('/api/v1/') }}"
