---

sensu_default_etcd_port: "{% if 'etcd' in groups %}2379{% else %}4001{% endif %}" 
sensu_etcd_port: "{{ etcd_port | default(sensu_default_etcd_port) }}"

sensu_flowdock_tags: "sensu {{ customer }} alerting"
sensu_flowdock_mail_from: "alerting@{{ customer_domain }}" 
sensu_flowdock_name_from: "Sensu_{{ customer }}"

sensu_manage_docker_storage: "{{ manage_docker_storage | default('true') }}"

sensu_deployment_type: "{{ deployment_type | default('openshift') }}"

sensu_openshift_etc_config: "{% if deployment_type == 'origin' or deployment_type == 'openshift-enterprise' %}origin{% else %}openshift{% endif %}"

sensu_openshift_base_api: "{{ openshift_base_api | default('/api/v1/') }}"

sensu_openshift_master_cluster_method: "{{ openshift_master_cluster_method | default('pacemaker') }}"

sensu_handlers: ["mailer"]

sensu_check_disk_all_atomic: "-b /host -e /host/var/lib/origin /host/var/lib/docker"
sensu_check_disk_all_rhel: "-b / -e /var/lib/origin /var/lib/docker"


#sensu_openshift_masters_deamon_name: "{% if deployment_type == 'origin' %}origin-master{% elif deployment_type == 'openshift-enterprise' %}atomic-openshift-master{% else %}openshift-master{% endif %}{% if sensu_openshift_master_cluster_method == 'native' %}-api{% endif %}"
#sensu_openshift_masters_deamon_name_controllers: "{% if deployment_type == 'origin' %}origin-master{% elif deployment_type == 'openshift-enterprise' %}atomic-openshift-master{% else %}openshift-master{% endif %}{% if sensu_openshift_master_cluster_method == 'native' %}-controllers{% endif %}"
